### ISSUE TITLE
Condense Location search filters

### ISSUE THREAD

**Issue by jmcorrigan** [datamade/CUAMP#23]

**Comment by jmcorrigan** [comment]
<img width="422" alt="screen shot 2017-03-17 at 4 37 56 pm" src="https://cloud.githubusercontent.com/assets/24783192/24063992/1acf0506-0b30-11e7-92ed-defce71ce2b8.png">

Condense these into a dropdown of some kind — not all displayed at once

**Comment by reginafcompton** [comment]
Solution: use accordion panels
<img width="403" alt="screen shot 2017-05-12 at 4 21 52 pm" src="https://cloud.githubusercontent.com/assets/13078679/26017443/30bc017c-372f-11e7-9689-62eba2b2dcee.png">
