### ISSUE TITLE
Add ward/municipality/community area toggle overlays

### ISSUE THREAD

**Issue by jmcorrigan** [datamade/CUAMP#24]

**Comment by jmcorrigan** [comment]
<img width="304" alt="screen shot 2017-03-17 at 4 35 23 pm" src="https://cloud.githubusercontent.com/assets/24783192/24063921/c2f6e9a2-0b2f-11e7-8a0e-0b5368ea44e0.png">

**Comment by jmcorrigan** [comment]
^^add a toggle option there for the overlay

**Comment by reginafcompton** [comment]
We are not going to prioritize this change, as we finalize the site. Closing!
