### ISSUE TITLE
detail modal could use some polish

### ISSUE THREAD

**Issue by derekeder** [datamade/CUAMP#39]
The modal popup is pretty sparse and could use some polish:

<img width="889" alt="screen shot 2017-08-16 at 2 56 00 pm" src="https://user-images.githubusercontent.com/919583/29382701-fecfe578-82bc-11e7-8dba-4dd412676e3c.png">

Ideas:
* condense the information into a smaller space (maybe use multiple columns)
* do we have a picture?
* group location info (address, ward, community area) together
* in addition to using icons to indicate status, lets use the words 'Yes' and 'No'

**Comment by reginafcompton** [comment]
I got started on this. One example:

<img width="1268" alt="screen shot 2017-08-22 at 5 15 32 pm" src="https://user-images.githubusercontent.com/13078679/29590046-9a2fcf16-875d-11e7-9564-e315ccf5d45d.png">

**Comment by reginafcompton** [comment]
Improved the header - the address links directly to Google maps, removed the "description" identifier, and place garden type designations at the top in italics.

<img width="666" alt="screen shot 2017-09-22 at 12 33 37 pm" src="https://user-images.githubusercontent.com/13078679/30756971-798d9d04-9f92-11e7-8ed6-50aa14f6ecdb.png">
