### ISSUE TITLE
list view button doesn't work

### ISSUE THREAD

**Issue by derekeder** [datamade/CUAMP#40]
Not sure if its just not implemented yet, but the list results button doesn't work for me:

<img width="385" alt="screen shot 2017-08-16 at 3 00 38 pm" src="https://user-images.githubusercontent.com/919583/29382901-ab4f3916-82bd-11e7-883b-542ccfa90636.png">

**Comment by reginafcompton** [comment]
Closed! (Caused by copy-and-paste idiocy in my refactor.....)
